import type { App, RespondArguments } from '@slack/bolt';
import type { WebClient } from '@slack/web-api';
import { randomBytes } from 'node:crypto';
import type { BackendClient } from '../clients/backend.js';
import type { Store } from '../store.js';
import type { NegotiationService } from '../services/negotiation.js';
import { helpText } from '../views/blocks.js';
import { normalizeSlackText, stableUuid, trackingId } from '../utils.js';

type Deps={store:Store;backend:BackendClient;negotiation:NegotiationService;publicBaseUrl:string;oauthTtlSeconds:number;allowedTeamId?:string};
const ephemeral=(text:string):RespondArguments=>({response_type:'ephemeral',text});
async function channelMembers(client:WebClient,channel:string){let cursor:string|undefined;const ids:string[]=[];do{const r=await client.conversations.members({channel,limit:200,cursor}) as any;ids.push(...(r.members??[]));cursor=r.response_metadata?.next_cursor||undefined;}while(cursor);const kept:string[]=[];for(const id of ids){const u=await client.users.info({user:id}) as any;if(!u.user?.is_bot&&!u.user?.deleted&&!u.user?.is_app_user)kept.push(id);}return kept;}

export function registerMeetu(app:App,deps:Deps){
  app.command('/meetu',async({command,ack,respond,client})=>{await ack();if(command.team_id==='')return;const [subRaw,...rest]=command.text.trim().split(/\s+/);const sub=(subRaw||'help').toLowerCase();
    try{
      if(deps.allowedTeamId&&command.team_id!==deps.allowedTeamId){await respond(ephemeral('허용되지 않은 워크스페이스예요.'));return;}
      if(sub==='help'){await respond(ephemeral(helpText));return;}
      if(sub==='connect'){const state=randomBytes(32).toString('base64url');deps.store.createOAuthState(state,command.team_id,command.user_id,new Date(Date.now()+deps.oauthTtlSeconds*1000).toISOString());const url=new URL('/oauth/connect',deps.publicBaseUrl);url.searchParams.set('state',state);await respond({response_type:'ephemeral',text:'Google Calendar 연결이 필요해요.',blocks:[{type:'section',text:{type:'mrkdwn',text:'Google Calendar를 Meet:U에 안전하게 연결해 주세요.'}},{type:'actions',elements:[{type:'button',url:url.toString(),action_id:'meetu_connect',text:{type:'plain_text',text:'Calendar 연결'}}]}]});return;}
      const user=deps.store.getUser(command.team_id,command.user_id);if(!user){await respond(ephemeral('Google Calendar 연결이 필요해요. `/meetu connect`를 실행해 주세요.'));return;}
      if(sub==='status'){const ch=deps.store.getChannel(command.team_id,command.channel_id);const active=ch&&deps.store.getActiveByRoom(ch.internalRoomId);await respond(ephemeral(`계정: ${user.calendarConnected?'연결됨':'Calendar 재연결 필요'}\n채널: ${ch?`room ${ch.internalRoomId}`:'미초기화'}${active?`\n협상: ${active.phase}`:''}`));return;}
      if(sub==='init'){const existing=deps.store.getChannel(command.team_id,command.channel_id);if(existing){await respond(ephemeral(`이미 room ${existing.internalRoomId}에 연결된 채널이에요.`));return;}const members=await channelMembers(client,command.channel_id);const linked=deps.store.getUsers(command.team_id,members);const linkedIds=new Set(linked.map(x=>x.slackUserId));const missing=members.filter(x=>!linkedIds.has(x));if(missing.length){await respond(ephemeral(`다음 참가자의 Calendar 연결이 필요해요: ${missing.map(x=>`<@${x}>`).join(', ')}`));return;}if(linked.length<2){await respond(ephemeral('연결된 참가자가 최소 2명 필요해요.'));return;}const title=rest.join(' ').trim()||command.channel_name.slice(0,40);const room=await deps.backend.createRoom(user.internalUserId,title,linked.map(x=>x.internalUserId).filter(x=>x!==user.internalUserId));const saved=deps.store.linkChannel(command.team_id,command.channel_id,room.roomId,command.user_id);await client.chat.postMessage({channel:command.channel_id,text:`✅ Meet:U 채팅방이 연결됐어요. (room ${saved.internalRoomId})`});return;}
      if(sub==='sync'){await respond(ephemeral('현재 백엔드에는 방 멤버 수정 API가 없어 상태 비교만 지원해요. 채널을 다시 초기화하려면 운영자에게 문의해 주세요.'));return;}
      if(sub==='schedule'){const text=normalizeSlackText(rest.join(' '));if(!text){await respond(ephemeral('요청을 입력해 주세요: `/meetu schedule 다음 주 화요일 오후 회의`'));return;}if(text.length>2000){await respond(ephemeral('요청은 2,000자 이하로 입력해 주세요.'));return;}await respond(ephemeral('일정 요청을 접수했어요. 채널에서 진행 상태를 확인해 주세요.'));const members=await channelMembers(client,command.channel_id);const key=`command:${stableUuid([command.team_id,command.channel_id,command.user_id,command.trigger_id,command.text].join(':'))}`;void deps.negotiation.schedule({teamId:command.team_id,channelId:command.channel_id,userId:command.user_id,text,requestKey:key,participants:members}).catch(async(e:any)=>{const id=trackingId();const message=e.message==='CHANNEL_NOT_LINKED'?'먼저 `/meetu init`을 실행해 주세요.':e.message==='ALREADY_ACTIVE'?'이미 이 채널에서 일정을 조율 중이에요.':`요청 처리 중 오류가 발생했어요. 추적 ID: ${id}`;await client.chat.postEphemeral({channel:command.channel_id,user:command.user_id,text:message});});return;}
      if(sub==='retry'){const last=deps.store.getLatest(command.team_id,command.channel_id);if(!last||!['failed','succeeded'].includes(last.status)){await respond(ephemeral('다시 시도할 완료된 요청이 없어요.'));return;}await respond(ephemeral('이전 조건으로 다시 조율을 시작할게요.'));const key=`retry:${stableUuid(`${command.team_id}:${command.channel_id}:${command.trigger_id}`)}`;void deps.negotiation.schedule({teamId:command.team_id,channelId:command.channel_id,userId:command.user_id,text:last.requestText,requestKey:key,participants:JSON.parse(last.participantSlackIds)}).catch(()=>client.chat.postEphemeral({channel:command.channel_id,user:command.user_id,text:'재시도하지 못했어요. 잠시 후 다시 실행해 주세요.'}));return;}
      await respond(ephemeral(helpText));
    }catch(e:any){const id=trackingId();console.error('command_failed',{teamId:command.team_id,channelId:command.channel_id,trackingId:id,error:e?.name});await respond(ephemeral(`요청을 처리하지 못했어요. 추적 ID: ${id}`));}
  });
  app.action('meetu_retry',async({ack,body,client})=>{await ack();const b=body as any;if(deps.allowedTeamId&&b.team?.id!==deps.allowedTeamId)return;const last=deps.store.getLatest(b.team.id,b.channel.id);if(!last)return;const key=`action:${stableUuid(`${b.team.id}:${b.channel.id}:${b.user.id}:${b.actions?.[0]?.action_ts??Date.now()}`)}`;void deps.negotiation.schedule({teamId:b.team.id,channelId:b.channel.id,userId:b.user.id,text:last.requestText,requestKey:key,participants:JSON.parse(last.participantSlackIds)}).catch(()=>client.chat.postEphemeral({channel:b.channel.id,user:b.user.id,text:'재시도하지 못했어요. 잠시 후 다시 실행해 주세요.'}));});
}
